[package]
name = "eunomia"
version = "0.0.1"
edition = "2021"

[lib]
name = "eunomia"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = {version = "4.2.1", features = ["derive"] }
regex = "1.7.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
